# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7c817d65f60e096169e28dc47f768884ed99847bfbf67385835c2ec8803346194478b4140320bf990280c4797683ec86f8650764839d372e5e02c691a159c1df

test:
  secret_key_base: fa94c82de489c415cf8ce7501b5134ad65c3338bd0d9fafc73fbc9a8ff4139f1101b168af2f570d6d6c25050b477688fe3067889a8370f4822d9e653f4e4640f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
